[activity_type_mapping]
"running" = "Running"
"cycling" = "Cycling (Sport)"
"mountain_biking" = "Mountain Biking"
"hiking" = "Hiking"
"walking" = "Walking"
"treadmill_running" = "Running"
"road_biking" = "Cycling (Sport)"
"trail_running" = "Trail"
"indoor_cycling" = "Cycling (Sport)"
"cycling_transport" = "Cycling (Transport)"
"elliptical" = "Other"
"swimming" = "Other"
"yoga" = "Other"
"strength_training" = "Other"
"resort_skiing" = "Skiing (Alpine)"
"resort_skiing_snowboarding_ws" = "Skiing (Alpine)"
"stand_up_paddleboarding_v2" = "Standup Paddleboarding"
"open_water_swimming" = "Open Water Swimming"
"inline_skating" = "Inline Skating"
"kayaking_v2" = "Canoeing"
"rowing_v2" = "Canoeing"
"e_bike_fitness" = "Cycling (Virtual)"
"gravel_cycling" = "Mountain Biking"
"pilates" = "Other"
"backcountry_skiing" = "Skiing (Cross Country)"
"tennis_v2" = "Padel (Outdoor)"
"e_bike_mountain" = "Mountain Biking (Electric)"
"lap_swimming" = "Open Water Swimming"
"other" = "Other"
"paddelball" = "Padel (Outdoor)"
"snorkeling" = "Open Water Swimming"
"indoor_rowing" = "Other"
"rock_climbing" = "Other"
"hiit" = "Other"
"winter_sports" = "Other"
"stair_climbing" = "Other"
"indoor_running" = "Running"
"street_running" = "Running"
"snow_shoe_ws" = "Snowshoes"
"indoor_cardio" = "Other"
"fitness_equipment" = "Other"
"driving_general" = "Other"
"bouldering" = "Other"
