[activity_type_mapping]
"running" = "Running"
"cycling" = "Cycling (Sport)"
"mountain_biking" = "Mountain Biking"
"hiking" = "Hiking"
"walking" = "Walking"
"treadmill_running" = "Running"
"road_biking" = "Cycling (Sport)"
"trail_running" = "Trail"
"indoor_cycling" = "Cycling (Sport)"
"cycling_transport" = "Cycling (Transport)"
"elliptical" = "Other"
"swimming" = "Other"
"yoga" = "Other"
"strength_training" = "Other"
"resort_skiing" = "Skiing (Alpine)"
"resort_skiing_snowboarding_ws" = "Skiing (Alpine)"
"stand_up_paddleboarding_v2" = "Standup Paddleboarding"
"open_water_swimming" = "Open Water Swimming"
"inline_skating" = "Inline Skating"
"kayaking_v2" = "Canoeing"
"rowing_v2" = "Canoeing"
